#include <stdio.h>
#include "reveal/core/connection.h"

int main( int argv, char* argc[] ) {

  // Note: argv needs to contain the connection id as a parameter generated by
  // the server and stored in the server side map which then should replace the
  // string "insert-rando-id" in the connection_c constructor
  std::string port_id = "insert-rando-id";

  Reveal::Core::connection_c connection( Reveal::Core::connection_c::IPC_CLIENT, port_id );  //< the connection to the planner

  if( connection.open() != Reveal::Core::connection_c::ERROR_NONE ) {
    printf( "simulator failed to open client ipc connection\nExiting\n" );
    return 1;
  }

  while(true) {
    std::string request, reply;
    if( connection.read( request ) != Reveal::Core::connection_c::ERROR_NONE ) {
      printf( "ERROR: connection failed to read request\nExiting" );
      return 1;
    }
    printf( "received request: %s\n", request.c_str() );

    reply = "good day";
    printf( "sending reply: %s\n", reply.c_str() ); 
    if( connection.write( reply ) != Reveal::Core::connection_c::ERROR_NONE ) {
      printf( "ERROR: connection failed to write reply\nExiting\n" );
      return 1;
    }
  }

  return 0;
}
